# Generated by Django 4.0.3 on 2022-03-05 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('recommender', '0001_add_similarity_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarity',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
