# Generated by Django 4.0.2 on 2022-02-21 13:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_load_users_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.CharField(default='1900', max_length=4)),
                ('imdbid', models.CharField(blank=True, max_length=20)),
                ('tmdbid', models.CharField(blank=True, max_length=20)),
                ('poster', models.URLField(blank=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to='app.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(
                related_name='watchlist', to='app.Movie'),
        ),
    ]
